### PR TITLE
Add FAQ Section

### LINKED ISSUE #4: Add FAQ Section
- Make a suitable FAQ Accordion for the website 
- Put some dummy texts as a faq answers for now
- Creativity is welcome
### Inspirations: 
- https://kiranworkspace.com/downloads/faq-ui-design-html-css/ 
- https://codemyui.com/faq-content-style-accordion/   
### FAQ Questions are:
- What is OpenCampus?
- How to Join OpenCampus?
- Benefits of Joining OpenCampus for Students?
- Benefits of Joining OpenCampus for Institutions?

### PR DESCRIPTION
**Pull request by priyanshumaitra**
Fixes #4

### CODE REVIEW

**Comment by thatsuman** [comment]
Could you please add snaps both for desktop and mobile view?

**Comment by priyanshumaitra** [comment]
> Could you please add snaps both for desktop and mobile view? 

Sure

**Comment by priyanshumaitra** [comment]
**Desktop View** 👇
image

**Mobile View** 👇
image

**Screen Cast** 👇
[Screencast from 10-10-22 02:54:10 PM IST.webm](https://user-images.githubusercontent.com/26964412/194836544-d6cb152e-ba2d-437c-8d05-23ff1a001fb3.webm)

**Comment by thatsuman** [comment]
Looks good! Merging 🎉

**Pull request merged**
